services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Bordeux\Bundle\GeoNameBundle\Import\TimeZoneImport:
  Bordeux\Bundle\GeoNameBundle\Import\AdministrativeImport:
  Bordeux\Bundle\GeoNameBundle\Import\GeoNameImport:
  Bordeux\Bundle\GeoNameBundle\Import\CountryImport:
  Bordeux\Bundle\GeoNameBundle\Import\HierarchyImport:
    
  Bordeux\Bundle\GeoNameBundle\Command\ImportCommand:
    arguments:
      $cacheDir: %kernel.cache_dir%
