<?php

namespace Bordeux\Bundle\GeoNameBundle\Repository;

/**
 * TimezoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimezoneRepository extends \Doctrine\ORM\EntityRepository
{
}
