on: [ push ]
name: Static analysis

jobs:
  php-code-check:
    name: PHP-CodeCheck
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - name: Run-Composer-Install
        run: composer install

      - name: Run-CodeStyle-Check
        run: composer cs:check

      - name: Run-Psalm
        run: composer cs:check

      - name: Run-Composer-Normalize
        run: composer normalize --dry-run